fix: dependency update to avoid: 'java.lang.NoSuchMethodError: org.apache.commons.lang3.Range.of(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lorg/apache/commons/lang3/Range;'