chore(deps): bump nifi.version from 1.23.2 to 1.24.0 (#135)
* chore(deps): bump nifi.version from 1.23.2 to 1.24.0

Bumps `nifi.version` from 1.23.2 to 1.24.0.

Updates `org.apache.nifi:nifi-utils` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-standard-record-utils` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-mock` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-mock-record-utils` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-standard-processors` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-record-serialization-services` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-schema-registry-service-api` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-record-path` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-standard-utils` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-ssl-context-service-api` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-security-utils` from 1.23.2 to 1.24.0

Updates `org.apache.nifi:nifi-standard-services-api-nar` from 1.23.2 to 1.24.0

---
updated-dependencies:
- dependency-name: org.apache.nifi:nifi-utils
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-standard-record-utils
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-mock
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-mock-record-utils
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-standard-processors
  dependency-type: direct:development
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-record-serialization-services
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-schema-registry-service-api
  dependency-type: direct:development
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-record-path
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-standard-utils
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-ssl-context-service-api
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-security-utils
  dependency-type: direct:production
  update-type: version-update:semver-minor
- dependency-name: org.apache.nifi:nifi-standard-services-api-nar
  dependency-type: direct:production
  update-type: version-update:semver-minor
...

Signed-off-by: dependabot[bot] <support@github.com>

* chore: update to Apache NiFi 1.24.0

* fix: dependency update to avoid: 'java.lang.NoSuchMethodError: org.apache.commons.lang3.Range.of(Ljava/lang/Comparable;Ljava/lang/Comparable;)Lorg/apache/commons/lang3/Range;'

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Jakub Bednar <jakub.bednar@gmail.com>